version: '3.2'
services:
  localstack:
    image: localstack/localstack-full
    container_name: localstack_demo
    network_mode: bridge
    ports:
      - '4563-4599:4563-4599'
      - '8088:8080'
    environment:
      - SERVICES=s3, lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'